#FROM nginx:latest
#COPY ./default.conf /etc/nginx/conf.d/default.conf
FROM nginx:latest   
COPY ./default.conf /etc/nginx/conf.d/default.conf
#COPY --from=buid ./default.conf /etc/nginx/conf.d/default.conf
